package com.linjicong.cloud.stat.controller;

import com.linjicong.cloud.stat.dao.mapper.acloud.*;
import com.linjicong.cloud.stat.dao.mapper.hcloud.*;
import com.linjicong.cloud.stat.dao.mapper.qcloud.*;
import com.linjicong.cloud.stat.dao.mapper.CommonMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@RestController
@CrossOrigin(origins = "*", maxAge = 3600)
public class ResourceController {

    @Autowired private HCloudEcsMapper hCloudEcsMapper;
    @Autowired private HCloudRdsMapper hCloudRdsMapper;
    @Autowired private HCloudElbMapper hCloudElbMapper;
    @Autowired private HCloudEvsMapper hCloudEvsMapper;
    @Autowired private HCloudVpcMapper hCloudVpcMapper;
    @Autowired private HCloudEipMapper hCloudEipMapper;
    @Autowired private HCloudImsMapper hCloudImsMapper;
    @Autowired private HCloudCbrMapper hCloudCbrMapper;
    @Autowired private HCloudBillsMonthlyBreakDownMapper hCloudBillsMonthlyBreakDownMapper;
    @Autowired private HCloudDcsMapper hCloudDcsMapper;
    @Autowired private HCloudDdsMapper hCloudDdsMapper;
    @Autowired private HCloudObsMapper hCloudObsMapper;
    @Autowired private HCloudSfsMapper hCloudSfsMapper;
    @Autowired private HCloudCesMetricMapper hCloudCesMetricMapper;
    @Autowired private HCloudDnsPrivateMapper hCloudDnsPrivateMapper;
    @Autowired private HCloudDnsPrivateRecordSetsMapper hCloudDnsPrivateRecordSetsMapper;
    @Autowired private HCloudCceMapper hCloudCceMapper;
    @Autowired private HCloudAuthDomainMapper hCloudAuthDomainMapper;
    @Autowired private HCloudUserMapper hCloudUserMapper;
    @Autowired private HCloudPermanentAccessKeyMapper hCloudPermanentAccessKeyMapper;
    @Autowired private HCloudResourceMapper hCloudResourceMapper;
    @Autowired private HCloudBillsFeeRecordsMapper hCloudBillsFeeRecordsMapper;
    @Autowired private HCloudResourceRecordDetailMapper hCloudResourceRecordDetailMapper;
    @Autowired private HCloudNatMapper hCloudNatMapper;
    @Autowired private HCloudFunctionGraphMapper hCloudFunctionGraphMapper;
    @Autowired private HCloudVpnMapper hCloudVpnMapper;
    @Autowired private HCloudGaussDbMapper hCloudGaussDbMapper;
    @Autowired private HCloudKmsMapper hCloudKmsMapper;
    @Autowired private HCloudWafMapper hCloudWafMapper;
    @Autowired private HCloudCtsMapper hCloudCtsMapper;
    @Autowired private HCloudKafkaMapper hCloudKafkaMapper;
    @Autowired private HCloudRocketMqMapper hCloudRocketMqMapper;
    @Autowired private HCloudRabbitMqMapper hCloudRabbitMqMapper;
    @Autowired private HCloudLtsMapper hCloudLtsMapper;
    @Autowired private HCloudCdnMapper hCloudCdnMapper;
    @Autowired private HCloudAntiDdosMapper hCloudAntiDdosMapper;
    @Autowired private HCloudHssMapper hCloudHssMapper;
    @Autowired private HCloudSwrMapper hCloudSwrMapper;
    @Autowired private HCloudSmnMapper hCloudSmnMapper;
    @Autowired private HCloudApigMapper hCloudApigMapper;
    @Autowired private HCloudAomMapper hCloudAomMapper;
    @Autowired private HCloudCssMapper hCloudCssMapper;
    @Autowired private HCloudCfwMapper hCloudCfwMapper;
    @Autowired private HCloudCcmMapper hCloudCcmMapper;
    @Autowired private HCloudDrsMapper hCloudDrsMapper;
    @Autowired private HCloudMrsMapper hCloudMrsMapper;
    @Autowired private HCloudAsMapper hCloudAsMapper;
    @Autowired private HCloudBmsMapper hCloudBmsMapper;
    @Autowired private HCloudWorkspaceMapper hCloudWorkspaceMapper;
    @Autowired private HCloudDliMapper hCloudDliMapper;
    @Autowired private HCloudDwsMapper hCloudDwsMapper;
    @Autowired private HCloudGaussDbNoSqlMapper hCloudGaussDbNoSqlMapper;
    @Autowired private HCloudGaussDbOpenGaussMapper hCloudGaussDbOpenGaussMapper;
    @Autowired private HCloudDdmMapper hCloudDdmMapper;
    @Autowired private HCloudCseMapper hCloudCseMapper;
    @Autowired private HCloudServiceStageMapper hCloudServiceStageMapper;
    @Autowired private HCloudCbhMapper hCloudCbhMapper;
    @Autowired private HCloudDbssMapper hCloudDbssMapper;
    @Autowired private HCloudVodMapper hCloudVodMapper;
    @Autowired private HCloudLiveMapper hCloudLiveMapper;
    @Autowired private HCloudOmsMapper hCloudOmsMapper;
    @Autowired private HCloudSdrsMapper hCloudSdrsMapper;
    @Autowired private HCloudSmsMapper hCloudSmsMapper;
    @Autowired private HCloudDscMapper hCloudDscMapper;
    @Autowired private HCloudRomaMapper hCloudRomaMapper;
    @Autowired private HCloudCphMapper hCloudCphMapper;
    @Autowired private HCloudErMapper hCloudErMapper;
    @Autowired private HCloudVpcepMapper hCloudVpcepMapper;
    @Autowired private HCloudIefMapper hCloudIefMapper;
    @Autowired private HCloudIotDaMapper hCloudIotDaMapper;
    @Autowired private HCloudDehMapper hCloudDehMapper;
    @Autowired private HCloudBcsMapper hCloudBcsMapper;
    @Autowired private HCloudDcMapper hCloudDcMapper;
    @Autowired private HCloudGaMapper hCloudGaMapper;
    @Autowired private HCloudEgMapper hCloudEgMapper;
    @Autowired private HCloudApmMapper hCloudApmMapper;
    @Autowired private HCloudCloudTableMapper hCloudCloudTableMapper;
    @Autowired private HCloudDataArtsStudioMapper hCloudDataArtsStudioMapper;
    @Autowired private HCloudDisMapper hCloudDisMapper;
    @Autowired private HCloudMasMapper hCloudMasMapper;
    @Autowired private HCloudMpcMapper hCloudMpcMapper;
    @Autowired private HCloudCloudDcMapper hCloudCloudDcMapper;
    @Autowired private HCloudKvsMapper hCloudKvsMapper;
    @Autowired private HCloudEdsMapper hCloudEdsMapper;
    @Autowired private HCloudTicsMapper hCloudTicsMapper;
    @Autowired private HCloudOrganizationsMapper hCloudOrganizationsMapper;
    @Autowired private HCloudRamMapper hCloudRamMapper;
    @Autowired private HCloudCocMapper hCloudCocMapper;

    @Autowired private ACloudAckMapper aCloudAckMapper;
    @Autowired private ACloudAcrMapper aCloudAcrMapper;
    @Autowired private ACloudActionTrailMapper aCloudActionTrailMapper;
    @Autowired private ACloudAlbMapper aCloudAlbMapper;
    @Autowired private ACloudAnalyticDbMapper aCloudAnalyticDbMapper;
    @Autowired private ACloudApiGatewayMapper aCloudApiGatewayMapper;
    @Autowired private ACloudCbhMapper aCloudCbhMapper;
    @Autowired private ACloudCdnMapper aCloudCdnMapper;
    @Autowired private ACloudCenMapper aCloudCenMapper;
    @Autowired private ACloudClickHouseMapper aCloudClickHouseMapper;
    @Autowired private ACloudCloudFirewallMapper aCloudCloudFirewallMapper;
    @Autowired private ACloudCmsMapper aCloudCmsMapper;
    @Autowired private ACloudConfigMapper aCloudConfigMapper;
    @Autowired private ACloudDdosMapper aCloudDdosMapper;
    @Autowired private ACloudDiskMapper aCloudDiskMapper;
    @Autowired private ACloudDnsDomainMapper aCloudDnsDomainMapper;
    @Autowired private ACloudDnsDomainRecordsMapper aCloudDnsDomainRecordsMapper;
    @Autowired private ACloudDscMapper aCloudDscMapper;
    @Autowired private ACloudDtsMapper aCloudDtsMapper;
    @Autowired private ACloudEcsMapper aCloudEcsMapper;
    @Autowired private ACloudEipMapper aCloudEipMapper;
    @Autowired private ACloudElasticsearchMapper aCloudElasticsearchMapper;
    @Autowired private ACloudEmrMapper aCloudEmrMapper;
    @Autowired private ACloudEssMapper aCloudEssMapper;
    @Autowired private ACloudFcMapper aCloudFcMapper;
    @Autowired private ACloudGaMapper aCloudGaMapper;
    @Autowired private ACloudHologresMapper aCloudHologresMapper;
    @Autowired private ACloudHssMapper aCloudHssMapper;
    @Autowired private ACloudIoTMapper aCloudIoTMapper;
    @Autowired private ACloudKafkaMapper aCloudKafkaMapper;
    @Autowired private ACloudKmsMapper aCloudKmsMapper;
    @Autowired private ACloudLindormMapper aCloudLindormMapper;
    @Autowired private ACloudLiveMapper aCloudLiveMapper;
    @Autowired private ACloudMaxComputeMapper aCloudMaxComputeMapper;
    @Autowired private ACloudMongoDbMapper aCloudMongoDbMapper;
    @Autowired private ACloudMseMapper aCloudMseMapper;
    @Autowired private ACloudNasMapper aCloudNasMapper;
    @Autowired private ACloudNatGatewayMapper aCloudNatGatewayMapper;
    @Autowired private ACloudNlbMapper aCloudNlbMapper;
    @Autowired private ACloudOosMapper aCloudOosMapper;
    @Autowired private ACloudOssMapper aCloudOssMapper;
    @Autowired private ACloudPolarDbMapper aCloudPolarDbMapper;
    @Autowired private ACloudQuotaMapper aCloudQuotaMapper;
    @Autowired private ACloudRabbitMqMapper aCloudRabbitMqMapper;
    @Autowired private ACloudRdsMapper aCloudRdsMapper;
    @Autowired private ACloudRedisMapper aCloudRedisMapper;
    @Autowired private ACloudRocketMQMapper aCloudRocketMQMapper;
    @Autowired private ACloudSaeMapper aCloudSaeMapper;
    @Autowired private ACloudSagMapper aCloudSagMapper;
    @Autowired private ACloudSecurityGroupMapper aCloudSecurityGroupMapper;
    @Autowired private ACloudSelectDbMapper aCloudSelectDbMapper;
    @Autowired private ACloudSlbMapper aCloudSlbMapper;
    @Autowired private ACloudSlsMapper aCloudSlsMapper;
    @Autowired private ACloudSmsMapper aCloudSmsMapper;
    @Autowired private ACloudSslMapper aCloudSslMapper;
    @Autowired private ACloudStorageGatewayMapper aCloudStorageGatewayMapper;
    @Autowired private ACloudVodMapper aCloudVodMapper;
    @Autowired private ACloudVpcEndpointMapper aCloudVpcEndpointMapper;
    @Autowired private ACloudVpcMapper aCloudVpcMapper;
    @Autowired private ACloudVpnGatewayMapper aCloudVpnGatewayMapper;
    @Autowired private ACloudWafMapper aCloudWafMapper;

    @Autowired private QCloudCvmMapper qCloudCvmMapper;
    @Autowired private QCloudCdbMapper qCloudCdbMapper;
    @Autowired private QCloudClbMapper qCloudClbMapper;
    @Autowired private QCloudCbsMapper qCloudCbsMapper;
    @Autowired private QCloudBillResourceSummaryMapper qCloudBillResourceSummaryMapper;
    @Autowired private QCloudVpcMapper qCloudVpcMapper;
    @Autowired private QCloudVpcSubnetMapper qCloudVpcSubnetMapper;
    @Autowired private QCloudEipMapper qCloudEipMapper;
    @Autowired private QCloudSecurityGroupMapper qCloudSecurityGroupMapper;
    @Autowired private QCloudCdnDomainMapper qCloudCdnDomainMapper;
    @Autowired private QCloudRedisMapper qCloudRedisMapper;
    @Autowired private QCloudMongoDbMapper qCloudMongoDbMapper;
    @Autowired private QCloudCynosDBMapper qCloudCynosDBMapper;
    @Autowired private QCloudPostgresqlMapper qCloudPostgresqlMapper;
    @Autowired private QCloudSqlserverMapper qCloudSqlserverMapper;
    @Autowired private QCloudNatGatewayMapper qCloudNatGatewayMapper;
    @Autowired private QCloudCfsMapper qCloudCfsMapper;
    @Autowired private QCloudDnsDomainMapper qCloudDnsDomainMapper;
    @Autowired private QCloudCosMapper qCloudCosMapper;
    @Autowired private QCloudScfMapper qCloudScfMapper;
    @Autowired private QCloudMariaDbMapper qCloudMariaDbMapper;
    @Autowired private QCloudDCDBMapper qCloudDCDBMapper;
    @Autowired private QCloudCkafkaMapper qCloudCkafkaMapper;
    @Autowired private QCloudRocketMQMapper qCloudRocketMQMapper;
    @Autowired private QCloudSSLMapper qCloudSSLMapper;
    @Autowired private QCloudWAFMapper qCloudWAFMapper;
    @Autowired private QCloudCLSMapper qCloudCLSMapper;
    @Autowired private QCloudMonitorMapper qCloudMonitorMapper;
    @Autowired private QCloudDomainMapper qCloudDomainMapper;
    @Autowired private QCloudTKEMapper qCloudTKEMapper;
    @Autowired private QCloudTCRMapper qCloudTCRMapper;
    @Autowired private QCloudESMapper qCloudESMapper;
    @Autowired private QCloudMemcachedMapper qCloudMemcachedMapper;
    @Autowired private QCloudKeeWiDBMapper qCloudKeeWiDBMapper;
    @Autowired private QCloudCTSDBMapper qCloudCTSDBMapper;
    @Autowired private QCloudCHDFSMapper qCloudCHDFSMapper;
    @Autowired private QCloudASMapper qCloudASMapper;
    @Autowired private QCloudLighthouseMapper qCloudLighthouseMapper;
    @Autowired private QCloudDCMapper qCloudDCMapper;
    @Autowired private QCloudRabbitMQMapper qCloudRabbitMQMapper;
    @Autowired private QCloudAPIGWMapper qCloudAPIGWMapper;
    @Autowired private QCloudBMSMapper qCloudBMSMapper;
    @Autowired private QCloudTDMQMapper qCloudTDMQMapper;
    @Autowired private QCloudOceanusMapper qCloudOceanusMapper;
    @Autowired private QCloudEMRMapper qCloudEMRMapper;
    @Autowired private QCloudGaapMapper qCloudGaapMapper;
    @Autowired private QCloudAgentGWMapper qCloudAgentGWMapper;
    @Autowired private QCloudAgentPlatformMapper qCloudAgentPlatformMapper;
    @Autowired private QCloudAppRenderMapper qCloudAppRenderMapper;
    @Autowired private QCloudASRMapper qCloudASRMapper;
    @Autowired private QCloudAuditMapper qCloudAuditMapper;
    @Autowired private QCloudBIMapper qCloudBIMapper;
    @Autowired private QCloudBastionMapper qCloudBastionMapper;
    @Autowired private QCloudBizProcessMapper qCloudBizProcessMapper;
    @Autowired private QCloudCACertMapper qCloudCACertMapper;
    @Autowired private QCloudCAPTCHAMapper qCloudCAPTCHAMapper;
    @Autowired private QCloudCHCMapper qCloudCHCMapper;
    @Autowired private QCloudCLB_gwMapper qCloudCLB_gwMapper;
    @Autowired private QCloudCloudBaseMapper qCloudCloudBaseMapper;
    @Autowired private QCloudCloudContactMapper qCloudCloudContactMapper;
    @Autowired private QCloudCloudHSMMapper qCloudCloudHSMMapper;
    @Autowired private QCloudCloudPhoneMapper qCloudCloudPhoneMapper;
    @Autowired private QCloudCloudStudioMapper qCloudCloudStudioMapper;
    @Autowired private QCloudCmqMapper qCloudCmqMapper;
    @Autowired private QCloudCodingDevopsMapper qCloudCodingDevopsMapper;
    @Autowired private QCloudConfigMapper qCloudConfigMapper;
    @Autowired private QCloudContentRecognizeMapper qCloudContentRecognizeMapper;
    @Autowired private QCloudContentSafeMapper qCloudContentSafeMapper;
    @Autowired private QCloudControlCenterMapper qCloudControlCenterMapper;
    @Autowired private QCloudCSPMapper qCloudCSPMapper;
    @Autowired private QCloudCSPGatewayMapper qCloudCSPGatewayMapper;
    @Autowired private QCloudCSSMapper qCloudCSSMapper;
    @Autowired private QCloudCWPMapper qCloudCWPMapper;
    @Autowired private QCloudCWP3Mapper qCloudCWP3Mapper;
    @Autowired private QCloudDDoSMapper qCloudDDoSMapper;
    @Autowired private QCloudDLCMapper qCloudDLCMapper;
    @Autowired private QCloudDNSPrivateMapper qCloudDNSPrivateMapper;
    @Autowired private QCloudDNSSecMapper qCloudDNSSecMapper;
    @Autowired private QCloudDataAuditMapper qCloudDataAuditMapper;
    @Autowired private QCloudDataSafeGovMapper qCloudDataSafeGovMapper;
    @Autowired private QCloudDeviceSafetyMapper qCloudDeviceSafetyMapper;
    @Autowired private QCloudDistIDMapper qCloudDistIDMapper;
    @Autowired private QCloudDocProcessMapper qCloudDocProcessMapper;
    @Autowired private QCloudDocsMapper qCloudDocsMapper;
    @Autowired private QCloudDomainRegMapper qCloudDomainRegMapper;
    @Autowired private QCloudEOMapper qCloudEOMapper;
    @Autowired private QCloudESignMapper qCloudESignMapper;
    @Autowired private QCloudEngWriteMapper qCloudEngWriteMapper;
    @Autowired private QCloudEventBusMapper qCloudEventBusMapper;
    @Autowired private QCloudExposedMgrMapper qCloudExposedMgrMapper;
    @Autowired private QCloudFaceMapper qCloudFaceMapper;
    @Autowired private QCloudFaceDeformMapper qCloudFaceDeformMapper;
    @Autowired private QCloudFaceFusionMapper qCloudFaceFusionMapper;
    @Autowired private QCloudFaceMakeupMapper qCloudFaceMakeupMapper;
    @Autowired private QCloudFaceSwapMapper qCloudFaceSwapMapper;
    @Autowired private QCloudGameAntiACEMapper qCloudGameAntiACEMapper;
    @Autowired private QCloudGameDBMapper qCloudGameDBMapper;
    @Autowired private QCloudGameServerMapper qCloudGameServerMapper;
    @Autowired private QCloudGameVoiceMapper qCloudGameVoiceMapper;
    @Autowired private QCloudGSEMapper qCloudGSEMapper;
    @Autowired private QCloudGTMMapper qCloudGTMMapper;
    @Autowired private QCloudGHPhoneMapper qCloudGHPhoneMapper;
    @Autowired private QCloudHBaseMapper qCloudHBaseMapper;
    @Autowired private QCloudHSMMapper qCloudHSMMapper;
    @Autowired private QCloudHealthDashMapper qCloudHealthDashMapper;
    @Autowired private QCloudHealthOmicsMapper qCloudHealthOmicsMapper;
    @Autowired private QCloudHealthReport2Mapper qCloudHealthReport2Mapper;
    @Autowired private QCloudICPBeianMapper qCloudICPBeianMapper;
    @Autowired private QCloudIOAMapper qCloudIOAMapper;
    @Autowired private QCloudImageProcess2Mapper qCloudImageProcess2Mapper;
    @Autowired private QCloudImageSearchMapper qCloudImageSearchMapper;
    @Autowired private QCloudIoTMapper qCloudIoTMapper;
    @Autowired private QCloudIoTDeviceMapper qCloudIoTDeviceMapper;
    @Autowired private QCloudIoTHubMapper qCloudIoTHubMapper;
    @Autowired private QCloudKMSMapper qCloudKMSMapper;
    @Autowired private QCloudKnowledgeEngineMapper qCloudKnowledgeEngineMapper;
    @Autowired private QCloudLiveMapper qCloudLiveMapper;
    @Autowired private QCloudLive2Mapper qCloudLive2Mapper;
    @Autowired private QCloudMailMapper qCloudMailMapper;
    @Autowired private QCloudMallTrafficMapper qCloudMallTrafficMapper;
    @Autowired private QCloudMathGradeMapper qCloudMathGradeMapper;
    @Autowired private QCloudMediaAssetMapper qCloudMediaAssetMapper;
    @Autowired private QCloudMeetingMapper qCloudMeetingMapper;
    @Autowired private QCloudMicroWedaMapper qCloudMicroWedaMapper;
    @Autowired private QCloudMiniSafeMapper qCloudMiniSafeMapper;
    @Autowired private QCloudMongoDB_CKafkaMapper qCloudMongoDB_CKafkaMapper;
    @Autowired private QCloudNMTMapper qCloudNMTMapper;
    @Autowired private QCloudNativeBuildMapper qCloudNativeBuildMapper;
    @Autowired private QCloudOCRMapper qCloudOCRMapper;
    @Autowired private QCloudOrgMapper qCloudOrgMapper;
    @Autowired private QCloudPenTestMapper qCloudPenTestMapper;
    @Autowired private QCloudPrivDNSMapper qCloudPrivDNSMapper;
    @Autowired private QCloudRegionMgrMapper qCloudRegionMgrMapper;
    @Autowired private QCloudRiskIdentifyMapper qCloudRiskIdentifyMapper;
    @Autowired private QCloudRTIEduMapper qCloudRTIEduMapper;
    @Autowired private QCloudRTIIndustrialMapper qCloudRTIIndustrialMapper;
    @Autowired private QCloudSafeAudioMapper qCloudSafeAudioMapper;
    @Autowired private QCloudSafeCenterMapper qCloudSafeCenterMapper;
    @Autowired private QCloudSafeDocMapper qCloudSafeDocMapper;
    @Autowired private QCloudSafeGuardMapper qCloudSafeGuardMapper;
    @Autowired private QCloudSafeImageMapper qCloudSafeImageMapper;
    @Autowired private QCloudSafeMonitorMapper qCloudSafeMonitorMapper;
    @Autowired private QCloudSafePlatformMapper qCloudSafePlatformMapper;
    @Autowired private QCloudSafeTextMapper qCloudSafeTextMapper;
    @Autowired private QCloudSafeVideoMapper qCloudSafeVideoMapper;
    @Autowired private QCloudSecCredentialMapper qCloudSecCredentialMapper;
    @Autowired private QCloudSecretMgrMapper qCloudSecretMgrMapper;
    @Autowired private QCloudSESMapper qCloudSESMapper;
    @Autowired private QCloudSmartAdvisorMapper qCloudSmartAdvisorMapper;
    @Autowired private QCloudSmartGuideMapper qCloudSmartGuideMapper;
    @Autowired private QCloudSmartViewMapper qCloudSmartViewMapper;
    @Autowired private QCloudSMSMapper qCloudSMSMapper;
    @Autowired private QCloudSmsSignMapper qCloudSmsSignMapper;
    @Autowired private QCloudSmsTemplateMapper qCloudSmsTemplateMapper;
    @Autowired private QCloudSpokenEvalMapper qCloudSpokenEvalMapper;
    @Autowired private QCloudSSLPodMapper qCloudSSLPodMapper;
    @Autowired private QCloudTAPDMapper qCloudTAPDMapper;
    @Autowired private QCloudTBAASMapper qCloudTBAASMapper;
    @Autowired private QCloudTCBMapper qCloudTCBMapper;
    @Autowired private QCloudTcaplusDBMapper qCloudTcaplusDBMapper;
    @Autowired private QCloudTcrEntMapper qCloudTcrEntMapper;
    @Autowired private QCloudTencentConnectMapper qCloudTencentConnectMapper;
    @Autowired private QCloudTendisMapper qCloudTendisMapper;
    @Autowired private QCloudTCHouseCMapper qCloudTCHouseCMapper;
    @Autowired private QCloudTCHouseDMapper qCloudTCHouseDMapper;
    @Autowired private QCloudTCHousePMapper qCloudTCHousePMapper;
    @Autowired private QCloudTIMapper qCloudTIMapper;
    @Autowired private QCloudTIHaiMapper qCloudTIHaiMapper;
    @Autowired private QCloudTokenHubMapper qCloudTokenHubMapper;
    @Autowired private QCloudTourismBigdataMapper qCloudTourismBigdataMapper;
    @Autowired private QCloudTRTCMapper qCloudTRTCMapper;
    @Autowired private QCloudTRTCRoomMapper qCloudTRTCRoomMapper;
    @Autowired private QCloudTSEMapper qCloudTSEMapper;
    @Autowired private QCloudTSFMapper qCloudTSFMapper;
    @Autowired private QCloudTTSMapper qCloudTTSMapper;
    @Autowired private QCloudVODMapper qCloudVODMapper;
    @Autowired private QCloudVODMediaMapper qCloudVODMediaMapper;
    @Autowired private QCloudVODProcessMapper qCloudVODProcessMapper;
    @Autowired private QCloudVoiceCloneMapper qCloudVoiceCloneMapper;
    @Autowired private QCloudVoiceMsgMapper qCloudVoiceMsgMapper;
    @Autowired private QCloudVulnMgrMapper qCloudVulnMgrMapper;
    @Autowired private QCloudWeDataMapper qCloudWeDataMapper;
    @Autowired private QCloudWeLinkMapper qCloudWeLinkMapper;
    @Autowired private QCloudWebSearchMapper qCloudWebSearchMapper;
    @Autowired private QCloudWedaMapper qCloudWedaMapper;


    /**
     * 查询资源列表，支持按账号筛选
     */
    private <T> List<T> queryByConfName(CommonMapper<T> mapper, String confName) {
        if (confName != null && !confName.isEmpty()) {
            return mapper.selectByConfName(confName);
        }
        return mapper.selectList(null);
    }

    @GetMapping("/huawei/{type}")
    public ResponseEntity<?> getHuaweiResources(@PathVariable String type, @RequestParam(required = false) String confName) {
        try {
            List<?> resources = switch (type.toLowerCase()) {
                case "ecs" -> queryByConfName(hCloudEcsMapper, confName);
                case "rds" -> queryByConfName(hCloudRdsMapper, confName);
                case "elb" -> queryByConfName(hCloudElbMapper, confName);
                case "evs" -> queryByConfName(hCloudEvsMapper, confName);
                case "vpc" -> queryByConfName(hCloudVpcMapper, confName);
                case "eip" -> queryByConfName(hCloudEipMapper, confName);
                case "ims" -> queryByConfName(hCloudImsMapper, confName);
                case "cbr" -> queryByConfName(hCloudCbrMapper, confName);
                case "bills" -> queryByConfName(hCloudBillsMonthlyBreakDownMapper, confName);
                case "dcs", "redis" -> queryByConfName(hCloudDcsMapper, confName);
                case "dds", "mongodb" -> queryByConfName(hCloudDdsMapper, confName);
                case "obs", "cos", "storage" -> queryByConfName(hCloudObsMapper, confName);
                case "sfs", "nas" -> queryByConfName(hCloudSfsMapper, confName);
                case "ces_metric", "metric" -> queryByConfName(hCloudCesMetricMapper, confName);
                case "dns_private" -> queryByConfName(hCloudDnsPrivateMapper, confName);
                case "dns_record_sets" -> queryByConfName(hCloudDnsPrivateRecordSetsMapper, confName);
                case "cce", "cluster" -> queryByConfName(hCloudCceMapper, confName);
                case "auth_domain" -> queryByConfName(hCloudAuthDomainMapper, confName);
                case "user", "iam" -> queryByConfName(hCloudUserMapper, confName);
                case "access_key" -> queryByConfName(hCloudPermanentAccessKeyMapper, confName);
                case "resource", "rms" -> queryByConfName(hCloudResourceMapper, confName);
                case "bills_fee_records" -> queryByConfName(hCloudBillsFeeRecordsMapper, confName);
                case "resource_record_detail" -> queryByConfName(hCloudResourceRecordDetailMapper, confName);
                case "nat" -> queryByConfName(hCloudNatMapper, confName);
                case "functiongraph", "faas" -> queryByConfName(hCloudFunctionGraphMapper, confName);
                case "vpn" -> queryByConfName(hCloudVpnMapper, confName);
                case "gaussdb" -> queryByConfName(hCloudGaussDbMapper, confName);
                case "kms" -> queryByConfName(hCloudKmsMapper, confName);
                case "waf" -> queryByConfName(hCloudWafMapper, confName);
                case "cts", "audit" -> queryByConfName(hCloudCtsMapper, confName);
                case "kafka" -> queryByConfName(hCloudKafkaMapper, confName);
                case "rocketmq" -> queryByConfName(hCloudRocketMqMapper, confName);
                case "rabbitmq" -> queryByConfName(hCloudRabbitMqMapper, confName);
                case "lts" -> queryByConfName(hCloudLtsMapper, confName);
                case "cdn" -> queryByConfName(hCloudCdnMapper, confName);
                case "antiddos", "ddos" -> queryByConfName(hCloudAntiDdosMapper, confName);
                case "hss" -> queryByConfName(hCloudHssMapper, confName);
                case "swr" -> queryByConfName(hCloudSwrMapper, confName);
                case "smn" -> queryByConfName(hCloudSmnMapper, confName);
                case "apig", "apigw" -> queryByConfName(hCloudApigMapper, confName);
                case "aom" -> queryByConfName(hCloudAomMapper, confName);
                case "css", "es" -> queryByConfName(hCloudCssMapper, confName);
                case "cfw" -> queryByConfName(hCloudCfwMapper, confName);
                case "ccm", "ssl" -> queryByConfName(hCloudCcmMapper, confName);
                case "drs" -> queryByConfName(hCloudDrsMapper, confName);
                case "mrs" -> queryByConfName(hCloudMrsMapper, confName);
                case "as" -> queryByConfName(hCloudAsMapper, confName);
                case "bms" -> queryByConfName(hCloudBmsMapper, confName);
                case "workspace", "wks" -> queryByConfName(hCloudWorkspaceMapper, confName);
                case "dli" -> queryByConfName(hCloudDliMapper, confName);
                case "dws" -> queryByConfName(hCloudDwsMapper, confName);
                case "gaussdbnosql" -> queryByConfName(hCloudGaussDbNoSqlMapper, confName);
                case "gaussdbopengauss" -> queryByConfName(hCloudGaussDbOpenGaussMapper, confName);
                case "ddm" -> queryByConfName(hCloudDdmMapper, confName);
                case "cse" -> queryByConfName(hCloudCseMapper, confName);
                case "servicestage" -> queryByConfName(hCloudServiceStageMapper, confName);
                case "cbh" -> queryByConfName(hCloudCbhMapper, confName);
                case "dbss" -> queryByConfName(hCloudDbssMapper, confName);
                case "vod" -> queryByConfName(hCloudVodMapper, confName);
                case "live" -> queryByConfName(hCloudLiveMapper, confName);
                case "oms" -> queryByConfName(hCloudOmsMapper, confName);
                case "sdrs" -> queryByConfName(hCloudSdrsMapper, confName);
                case "sms" -> queryByConfName(hCloudSmsMapper, confName);
                case "dsc" -> queryByConfName(hCloudDscMapper, confName);
                case "roma" -> queryByConfName(hCloudRomaMapper, confName);
                case "cph" -> queryByConfName(hCloudCphMapper, confName);
                case "er" -> queryByConfName(hCloudErMapper, confName);
                case "vpcep" -> queryByConfName(hCloudVpcepMapper, confName);
                case "ief" -> queryByConfName(hCloudIefMapper, confName);
                case "iotda", "iot" -> queryByConfName(hCloudIotDaMapper, confName);
                case "deh" -> queryByConfName(hCloudDehMapper, confName);
                case "bcs" -> queryByConfName(hCloudBcsMapper, confName);
                case "dc" -> queryByConfName(hCloudDcMapper, confName);
                case "ga" -> queryByConfName(hCloudGaMapper, confName);
                case "eg" -> queryByConfName(hCloudEgMapper, confName);
                case "apm" -> queryByConfName(hCloudApmMapper, confName);
                case "cloudtable" -> queryByConfName(hCloudCloudTableMapper, confName);
                case "dataartsstudio", "dataarts" -> queryByConfName(hCloudDataArtsStudioMapper, confName);
                case "dis" -> queryByConfName(hCloudDisMapper, confName);
                case "mas" -> queryByConfName(hCloudMasMapper, confName);
                case "mpc" -> queryByConfName(hCloudMpcMapper, confName);
                case "clouddc" -> queryByConfName(hCloudCloudDcMapper, confName);
                case "kvs" -> queryByConfName(hCloudKvsMapper, confName);
                case "eds" -> queryByConfName(hCloudEdsMapper, confName);
                case "tics" -> queryByConfName(hCloudTicsMapper, confName);
                case "organizations", "org" -> queryByConfName(hCloudOrganizationsMapper, confName);
                case "ram" -> queryByConfName(hCloudRamMapper, confName);
                case "coc" -> queryByConfName(hCloudCocMapper, confName);
                default -> null;
            };
            if (resources != null) { return ResponseEntity.ok(resources); }
            else { return ResponseEntity.badRequest().body("unsupported type: " + type); }
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("query failed: " + e.getMessage());
        }
    }

    @GetMapping("/tencent/{type}")
    public ResponseEntity<?> getTencentResources(@PathVariable String type, @RequestParam(required = false) String confName) {
        try {
            List<?> resources = switch (type.toLowerCase()) {
                case "cvm" -> queryByConfName(qCloudCvmMapper, confName);
                case "cdb" -> queryByConfName(qCloudCdbMapper, confName);
                case "clb" -> queryByConfName(qCloudClbMapper, confName);
                case "cbs" -> queryByConfName(qCloudCbsMapper, confName);
                case "bills" -> queryByConfName(qCloudBillResourceSummaryMapper, confName);
                case "vpc" -> queryByConfName(qCloudVpcMapper, confName);
                case "subnet" -> queryByConfName(qCloudVpcSubnetMapper, confName);
                case "eip" -> queryByConfName(qCloudEipMapper, confName);
                case "sg", "securitygroup" -> queryByConfName(qCloudSecurityGroupMapper, confName);
                case "cdn" -> queryByConfName(qCloudCdnDomainMapper, confName);
                case "redis" -> queryByConfName(qCloudRedisMapper, confName);
                case "mongodb" -> queryByConfName(qCloudMongoDbMapper, confName);
                case "cynosdb" -> queryByConfName(qCloudCynosDBMapper, confName);
                case "postgresql", "pg" -> queryByConfName(qCloudPostgresqlMapper, confName);
                case "sqlserver" -> queryByConfName(qCloudSqlserverMapper, confName);
                case "nat" -> queryByConfName(qCloudNatGatewayMapper, confName);
                case "cfs" -> queryByConfName(qCloudCfsMapper, confName);
                case "dns" -> queryByConfName(qCloudDnsDomainMapper, confName);
                case "cos" -> queryByConfName(qCloudCosMapper, confName);
                                case "scf" -> queryByConfName(qCloudScfMapper, confName);
                case "mariadb" -> queryByConfName(qCloudMariaDbMapper, confName);
                case "dcdb" -> queryByConfName(qCloudDCDBMapper, confName);
                case "ckafka" -> queryByConfName(qCloudCkafkaMapper, confName);
                case "rocketmq" -> queryByConfName(qCloudRocketMQMapper, confName);
                case "ssl" -> queryByConfName(qCloudSSLMapper, confName);
                case "waf" -> queryByConfName(qCloudWAFMapper, confName);
                case "cls" -> queryByConfName(qCloudCLSMapper, confName);
                case "monitor" -> queryByConfName(qCloudMonitorMapper, confName);
                case "domain" -> queryByConfName(qCloudDomainMapper, confName);
                case "tke" -> queryByConfName(qCloudTKEMapper, confName);
                case "tcr" -> queryByConfName(qCloudTCRMapper, confName);
                case "es" -> queryByConfName(qCloudESMapper, confName);

                                case "memcached" -> queryByConfName(qCloudMemcachedMapper, confName);
                case "keewidb" -> queryByConfName(qCloudKeeWiDBMapper, confName);
                case "ctsdb" -> queryByConfName(qCloudCTSDBMapper, confName);
                case "chdfs" -> queryByConfName(qCloudCHDFSMapper, confName);
                case "as" -> queryByConfName(qCloudASMapper, confName);
                case "lighthouse" -> queryByConfName(qCloudLighthouseMapper, confName);
                case "dc" -> queryByConfName(qCloudDCMapper, confName);
                case "rabbitmq" -> queryByConfName(qCloudRabbitMQMapper, confName);
                case "apigw" -> queryByConfName(qCloudAPIGWMapper, confName);
                case "bms" -> queryByConfName(qCloudBMSMapper, confName);
                case "tdmq" -> queryByConfName(qCloudTDMQMapper, confName);
                case "oceanus" -> queryByConfName(qCloudOceanusMapper, confName);
                case "emr" -> queryByConfName(qCloudEMRMapper, confName);
                case "gaap" -> queryByConfName(qCloudGaapMapper, confName);
                case "agentgw" -> queryByConfName(qCloudAgentGWMapper, confName);
                case "agentplatform" -> queryByConfName(qCloudAgentPlatformMapper, confName);
                case "apprender" -> queryByConfName(qCloudAppRenderMapper, confName);
                case "asr" -> queryByConfName(qCloudASRMapper, confName);
                case "audit" -> queryByConfName(qCloudAuditMapper, confName);
                case "bi" -> queryByConfName(qCloudBIMapper, confName);
                case "bastion" -> queryByConfName(qCloudBastionMapper, confName);
                case "bizprocess" -> queryByConfName(qCloudBizProcessMapper, confName);
                case "cacert" -> queryByConfName(qCloudCACertMapper, confName);
                case "captcha" -> queryByConfName(qCloudCAPTCHAMapper, confName);
                case "chc" -> queryByConfName(qCloudCHCMapper, confName);
                case "clbgw" -> queryByConfName(qCloudCLB_gwMapper, confName);
                case "cloudbase" -> queryByConfName(qCloudCloudBaseMapper, confName);
                case "cloudcontact" -> queryByConfName(qCloudCloudContactMapper, confName);
                case "cloudhsm" -> queryByConfName(qCloudCloudHSMMapper, confName);
                case "cloudphone" -> queryByConfName(qCloudCloudPhoneMapper, confName);
                case "cloudstudio" -> queryByConfName(qCloudCloudStudioMapper, confName);
                case "cmq" -> queryByConfName(qCloudCmqMapper, confName);
                case "codingdevops" -> queryByConfName(qCloudCodingDevopsMapper, confName);
                case "config" -> queryByConfName(qCloudConfigMapper, confName);
                case "contentrecognize" -> queryByConfName(qCloudContentRecognizeMapper, confName);
                case "contentsafe" -> queryByConfName(qCloudContentSafeMapper, confName);
                case "controlcenter" -> queryByConfName(qCloudControlCenterMapper, confName);
                case "csp" -> queryByConfName(qCloudCSPMapper, confName);
                case "cspgateway" -> queryByConfName(qCloudCSPGatewayMapper, confName);
                case "css" -> queryByConfName(qCloudCSSMapper, confName);
                case "cwp" -> queryByConfName(qCloudCWPMapper, confName);
                case "cwp3" -> queryByConfName(qCloudCWP3Mapper, confName);
                case "ddos" -> queryByConfName(qCloudDDoSMapper, confName);
                case "dlc" -> queryByConfName(qCloudDLCMapper, confName);
                case "dnsprivate" -> queryByConfName(qCloudDNSPrivateMapper, confName);
                case "dnssec" -> queryByConfName(qCloudDNSSecMapper, confName);
                case "dataaudit" -> queryByConfName(qCloudDataAuditMapper, confName);
                case "datasafegov" -> queryByConfName(qCloudDataSafeGovMapper, confName);
                case "devicesafety" -> queryByConfName(qCloudDeviceSafetyMapper, confName);
                case "distid" -> queryByConfName(qCloudDistIDMapper, confName);
                case "docprocess" -> queryByConfName(qCloudDocProcessMapper, confName);
                case "docs" -> queryByConfName(qCloudDocsMapper, confName);
                case "domainreg" -> queryByConfName(qCloudDomainRegMapper, confName);
                case "eo" -> queryByConfName(qCloudEOMapper, confName);
                case "esign" -> queryByConfName(qCloudESignMapper, confName);
                case "engwrite" -> queryByConfName(qCloudEngWriteMapper, confName);
                case "eventbus" -> queryByConfName(qCloudEventBusMapper, confName);
                case "exposedmgr" -> queryByConfName(qCloudExposedMgrMapper, confName);
                case "face" -> queryByConfName(qCloudFaceMapper, confName);
                case "facefusion" -> queryByConfName(qCloudFaceFusionMapper, confName);
                case "facemakeup" -> queryByConfName(qCloudFaceMakeupMapper, confName);
                case "faceswap" -> queryByConfName(qCloudFaceSwapMapper, confName);
                case "gameantiace" -> queryByConfName(qCloudGameAntiACEMapper, confName);
                case "gamedb" -> queryByConfName(qCloudGameDBMapper, confName);
                case "gameserver" -> queryByConfName(qCloudGameServerMapper, confName);
                case "gamevoice" -> queryByConfName(qCloudGameVoiceMapper, confName);
                case "gse" -> queryByConfName(qCloudGSEMapper, confName);
                case "gtm" -> queryByConfName(qCloudGTMMapper, confName);
                case "ghphone" -> queryByConfName(qCloudGHPhoneMapper, confName);
                case "hbase" -> queryByConfName(qCloudHBaseMapper, confName);
                case "hsm" -> queryByConfName(qCloudHSMMapper, confName);
                case "healthdash" -> queryByConfName(qCloudHealthDashMapper, confName);
                case "healthomics" -> queryByConfName(qCloudHealthOmicsMapper, confName);
                case "healthreport" -> queryByConfName(qCloudHealthReport2Mapper, confName);
                case "icpbeian" -> queryByConfName(qCloudICPBeianMapper, confName);
                case "ioa" -> queryByConfName(qCloudIOAMapper, confName);
                case "imageprocess" -> queryByConfName(qCloudImageProcess2Mapper, confName);
                case "imagesearch" -> queryByConfName(qCloudImageSearchMapper, confName);
                case "iot" -> queryByConfName(qCloudIoTMapper, confName);
                case "iotdevice" -> queryByConfName(qCloudIoTDeviceMapper, confName);
                case "iothub" -> queryByConfName(qCloudIoTHubMapper, confName);
                case "kms" -> queryByConfName(qCloudKMSMapper, confName);
                case "knowledgeengine" -> queryByConfName(qCloudKnowledgeEngineMapper, confName);
                case "live" -> queryByConfName(qCloudLiveMapper, confName);
                case "live2" -> queryByConfName(qCloudLive2Mapper, confName);
                case "mail" -> queryByConfName(qCloudMailMapper, confName);
                case "malltraffic" -> queryByConfName(qCloudMallTrafficMapper, confName);
                case "mathgrade" -> queryByConfName(qCloudMathGradeMapper, confName);
                case "mediaasset" -> queryByConfName(qCloudMediaAssetMapper, confName);
                case "meeting" -> queryByConfName(qCloudMeetingMapper, confName);
                case "microweda" -> queryByConfName(qCloudMicroWedaMapper, confName);
                case "minisafe" -> queryByConfName(qCloudMiniSafeMapper, confName);
                case "mongodbckafka" -> queryByConfName(qCloudMongoDB_CKafkaMapper, confName);
                case "nmt" -> queryByConfName(qCloudNMTMapper, confName);
                case "nativebuild" -> queryByConfName(qCloudNativeBuildMapper, confName);
                case "ocr" -> queryByConfName(qCloudOCRMapper, confName);
                case "org" -> queryByConfName(qCloudOrgMapper, confName);
                case "pentest" -> queryByConfName(qCloudPenTestMapper, confName);
                case "privdns" -> queryByConfName(qCloudPrivDNSMapper, confName);
                case "regionmgr" -> queryByConfName(qCloudRegionMgrMapper, confName);
                case "riskidentify" -> queryByConfName(qCloudRiskIdentifyMapper, confName);
                case "rtiedu" -> queryByConfName(qCloudRTIEduMapper, confName);
                case "rtiindustrial" -> queryByConfName(qCloudRTIIndustrialMapper, confName);
                case "safeaudio" -> queryByConfName(qCloudSafeAudioMapper, confName);
                case "safecenter" -> queryByConfName(qCloudSafeCenterMapper, confName);
                case "safedoc" -> queryByConfName(qCloudSafeDocMapper, confName);
                case "safeguard" -> queryByConfName(qCloudSafeGuardMapper, confName);
                case "safeimage" -> queryByConfName(qCloudSafeImageMapper, confName);
                case "safemonitor" -> queryByConfName(qCloudSafeMonitorMapper, confName);
                case "safeplatform" -> queryByConfName(qCloudSafePlatformMapper, confName);
                case "safetext" -> queryByConfName(qCloudSafeTextMapper, confName);
                case "safevideo" -> queryByConfName(qCloudSafeVideoMapper, confName);
                case "seccredential" -> queryByConfName(qCloudSecCredentialMapper, confName);
                case "secretmgr" -> queryByConfName(qCloudSecretMgrMapper, confName);
                case "ses" -> queryByConfName(qCloudSESMapper, confName);
                case "smartadvisor" -> queryByConfName(qCloudSmartAdvisorMapper, confName);
                case "smartguide" -> queryByConfName(qCloudSmartGuideMapper, confName);
                case "smartview" -> queryByConfName(qCloudSmartViewMapper, confName);
                case "sms" -> queryByConfName(qCloudSMSMapper, confName);
                case "smssign" -> queryByConfName(qCloudSmsSignMapper, confName);
                case "smstemplate" -> queryByConfName(qCloudSmsTemplateMapper, confName);
                case "spokeneval" -> queryByConfName(qCloudSpokenEvalMapper, confName);
                case "sslpod" -> queryByConfName(qCloudSSLPodMapper, confName);
                case "tapd" -> queryByConfName(qCloudTAPDMapper, confName);
                case "tbaas" -> queryByConfName(qCloudTBAASMapper, confName);
                case "tcb" -> queryByConfName(qCloudTCBMapper, confName);
                case "tcaplusdb" -> queryByConfName(qCloudTcaplusDBMapper, confName);
                case "tcrent" -> queryByConfName(qCloudTcrEntMapper, confName);
                case "tencentconnect" -> queryByConfName(qCloudTencentConnectMapper, confName);
                case "tendis" -> queryByConfName(qCloudTendisMapper, confName);
                case "tchousec" -> queryByConfName(qCloudTCHouseCMapper, confName);
                case "tchoused" -> queryByConfName(qCloudTCHouseDMapper, confName);
                case "tchousep" -> queryByConfName(qCloudTCHousePMapper, confName);
                case "ti" -> queryByConfName(qCloudTIMapper, confName);
                case "tihai" -> queryByConfName(qCloudTIHaiMapper, confName);
                case "tokenhub" -> queryByConfName(qCloudTokenHubMapper, confName);
                case "tourismbigdata" -> queryByConfName(qCloudTourismBigdataMapper, confName);
                case "trtc" -> queryByConfName(qCloudTRTCMapper, confName);
                case "trtcroom" -> queryByConfName(qCloudTRTCRoomMapper, confName);
                case "tse" -> queryByConfName(qCloudTSEMapper, confName);
                case "tsf" -> queryByConfName(qCloudTSFMapper, confName);
                case "tts" -> queryByConfName(qCloudTTSMapper, confName);
                case "vod" -> queryByConfName(qCloudVODMapper, confName);
                case "vodmedia" -> queryByConfName(qCloudVODMediaMapper, confName);
                case "vodprocess" -> queryByConfName(qCloudVODProcessMapper, confName);
                case "voiceclone" -> queryByConfName(qCloudVoiceCloneMapper, confName);
                case "voicemsg" -> queryByConfName(qCloudVoiceMsgMapper, confName);
                case "vulnmgr" -> queryByConfName(qCloudVulnMgrMapper, confName);
                case "wedata" -> queryByConfName(qCloudWeDataMapper, confName);
                case "welink" -> queryByConfName(qCloudWeLinkMapper, confName);
                case "websearch" -> queryByConfName(qCloudWebSearchMapper, confName);
                case "weda" -> queryByConfName(qCloudWedaMapper, confName);

                default -> null;
            };
            if (resources != null) { return ResponseEntity.ok(resources); }
            else { return ResponseEntity.badRequest().body("unsupported type: " + type); }
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("query failed: " + e.getMessage());
        }
    }

    @GetMapping("/aliyun/{type}")
    public ResponseEntity<?> getAliyunResources(@PathVariable String type, @RequestParam(required = false) String confName) {
        try {
            List<?> resources = switch (type.toLowerCase()) {
                case "ack" -> queryByConfName(aCloudAckMapper, confName);
                case "acr" -> queryByConfName(aCloudAcrMapper, confName);
                case "actiontrail" -> queryByConfName(aCloudActionTrailMapper, confName);
                case "alb" -> queryByConfName(aCloudAlbMapper, confName);
                case "analyticdb" -> queryByConfName(aCloudAnalyticDbMapper, confName);
                case "apigateway" -> queryByConfName(aCloudApiGatewayMapper, confName);
                case "cbh" -> queryByConfName(aCloudCbhMapper, confName);
                case "cdn" -> queryByConfName(aCloudCdnMapper, confName);
                case "cen" -> queryByConfName(aCloudCenMapper, confName);
                case "clickhouse" -> queryByConfName(aCloudClickHouseMapper, confName);
                case "cloudfirewall" -> queryByConfName(aCloudCloudFirewallMapper, confName);
                case "cms" -> queryByConfName(aCloudCmsMapper, confName);
                case "config" -> queryByConfName(aCloudConfigMapper, confName);
                case "ddos" -> queryByConfName(aCloudDdosMapper, confName);
                case "disk" -> queryByConfName(aCloudDiskMapper, confName);
                case "dns" -> queryByConfName(aCloudDnsDomainMapper, confName);
                case "dns_records" -> queryByConfName(aCloudDnsDomainRecordsMapper, confName);
                case "dsc" -> queryByConfName(aCloudDscMapper, confName);
                case "dts" -> queryByConfName(aCloudDtsMapper, confName);
                case "ecs" -> queryByConfName(aCloudEcsMapper, confName);
                case "eip" -> queryByConfName(aCloudEipMapper, confName);
                case "elasticsearch" -> queryByConfName(aCloudElasticsearchMapper, confName);
                case "emr" -> queryByConfName(aCloudEmrMapper, confName);
                case "ess" -> queryByConfName(aCloudEssMapper, confName);
                case "fc" -> queryByConfName(aCloudFcMapper, confName);
                case "ga" -> queryByConfName(aCloudGaMapper, confName);
                case "hologres" -> queryByConfName(aCloudHologresMapper, confName);
                case "hss" -> queryByConfName(aCloudHssMapper, confName);
                case "iot" -> queryByConfName(aCloudIoTMapper, confName);
                case "kafka" -> queryByConfName(aCloudKafkaMapper, confName);
                case "kms" -> queryByConfName(aCloudKmsMapper, confName);
                case "lindorm" -> queryByConfName(aCloudLindormMapper, confName);
                case "live" -> queryByConfName(aCloudLiveMapper, confName);
                case "maxcompute" -> queryByConfName(aCloudMaxComputeMapper, confName);
                case "mongodb" -> queryByConfName(aCloudMongoDbMapper, confName);
                case "mse" -> queryByConfName(aCloudMseMapper, confName);
                case "nas" -> queryByConfName(aCloudNasMapper, confName);
                case "nat" -> queryByConfName(aCloudNatGatewayMapper, confName);
                case "nlb" -> queryByConfName(aCloudNlbMapper, confName);
                case "oos" -> queryByConfName(aCloudOosMapper, confName);
                case "oss" -> queryByConfName(aCloudOssMapper, confName);
                case "polardb" -> queryByConfName(aCloudPolarDbMapper, confName);
                case "quota" -> queryByConfName(aCloudQuotaMapper, confName);
                case "rabbitmq" -> queryByConfName(aCloudRabbitMqMapper, confName);
                case "rds" -> queryByConfName(aCloudRdsMapper, confName);
                case "redis" -> queryByConfName(aCloudRedisMapper, confName);
                case "rocketmq" -> queryByConfName(aCloudRocketMQMapper, confName);
                case "sae" -> queryByConfName(aCloudSaeMapper, confName);
                case "sag" -> queryByConfName(aCloudSagMapper, confName);
                case "securitygroup" -> queryByConfName(aCloudSecurityGroupMapper, confName);
                case "selectdb" -> queryByConfName(aCloudSelectDbMapper, confName);
                case "slb" -> queryByConfName(aCloudSlbMapper, confName);
                case "sls" -> queryByConfName(aCloudSlsMapper, confName);
                case "sms" -> queryByConfName(aCloudSmsMapper, confName);
                case "ssl" -> queryByConfName(aCloudSslMapper, confName);
                case "storagegateway" -> queryByConfName(aCloudStorageGatewayMapper, confName);
                case "vod" -> queryByConfName(aCloudVodMapper, confName);
                case "vpcendpoint" -> queryByConfName(aCloudVpcEndpointMapper, confName);
                case "vpc" -> queryByConfName(aCloudVpcMapper, confName);
                case "vpngateway" -> queryByConfName(aCloudVpnGatewayMapper, confName);
                case "waf" -> queryByConfName(aCloudWafMapper, confName);
                default -> null;
            };
            if (resources != null) { return ResponseEntity.ok(resources); }
            else { return ResponseEntity.badRequest().body("unsupported type: " + type); }
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("query failed: " + e.getMessage());
        }
    }
}
