-- New Tencent Cloud Resource Tables DDL

CREATE TABLE IF NOT EXISTS q_cloud_vpc (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, vpc_name varchar(255), vpc_id varchar(255), cidr_block varchar(255), is_default tinyint(1), enable_multicast tinyint(1), created_time varchar(255), dns_server_set json, domain_name varchar(255), dhcp_options_id varchar(255), tags json, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_vpc_subnet (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, vpc_id varchar(255), subnet_id varchar(255), subnet_name varchar(255), cidr_block varchar(255), is_default tinyint(1), enable_broadcast tinyint(1), zone varchar(255), route_table_id varchar(255), created_time varchar(255), available_ip_address_count bigint, ipv6_cidr_block varchar(255), network_acl_id varchar(255), tags json, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_eip (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, address_id varchar(255), address_name varchar(255), address_status varchar(255), address_ip varchar(255), instance_id varchar(255), instance_type varchar(255), created_time varchar(255), internet_charge_type varchar(255), internet_max_bandwidth_out bigint, address_type varchar(255), private_address_ip varchar(255), deadline_date varchar(255), tags json, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_security_group (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, security_group_id varchar(255), security_group_name varchar(255), security_group_desc varchar(255), project_id bigint, is_default tinyint(1), created_time varchar(255), tags json, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_cdn_domain (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, resource_id varchar(255), domain varchar(255), cname varchar(255), status varchar(255), project_id bigint, area varchar(255), service_type varchar(255), create_time varchar(255), update_time varchar(255), origin json, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_cos (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, name varchar(255), location varchar(255), creation_date varchar(255), bucket_uin varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_redis (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_name varchar(255), instance_id varchar(255), appid bigint, project_id bigint, region_id bigint, zone_id bigint, redis_shard_num bigint, redis_replicas_num bigint, redis_shard_size bigint, size bigint, status bigint, bandwidth bigint, un_shard_conn_limit bigint, pay_mode bigint, deadline_time bigint, auto_renew_flag bigint, createtime bigint, vip varchar(255), vpc_id bigint, subnet_id bigint, net_limit bigint, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_mongodb (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_id varchar(255), instance_name varchar(255), cluster_type bigint, region varchar(255), zone varchar(255), memory bigint, volume bigint, cpu_num bigint, machine_type varchar(255), max_conns bigint, mongo_version varchar(255), pay_mode varchar(255), project_id bigint, status bigint, vip varchar(255), vport bigint, create_time varchar(255), dead_line varchar(255), vpc_id bigint, subnet_id bigint, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_cynosdb (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_id varchar(255), instance_name varchar(255), status varchar(255), status_desc varchar(255), db_type varchar(255), memory bigint, storage_limit bigint, storage_used bigint, cpu_num bigint, instance_type varchar(255), vpc_id bigint, subnet_id bigint, vip varchar(255), vport bigint, zone varchar(255), db_engine varchar(255), db_version varchar(255), create_time varchar(255), dead_line_time varchar(255), pay_mode varchar(255), cluster_id varchar(255), cluster_name varchar(255), project_id bigint, max_conns bigint, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_postgresql (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, db_instance_id varchar(255), db_instance_name varchar(255), project_id bigint, region varchar(255), zone varchar(255), db_instance_memory bigint, db_instance_storage bigint, db_instance_status varchar(255), db_instance_type varchar(255), db_version varchar(255), db_engine varchar(255), vpc_id varchar(255), subnet_id varchar(255), vip varchar(255), vport bigint, create_time varchar(255), dead_line_time varchar(255), pay_type varchar(255), auto_renew bigint, db_instance_cpu bigint, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_sqlserver (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_id varchar(255), name varchar(255), project_id bigint, zone varchar(255), vip varchar(255), vport bigint, create_time varchar(255), end_time varchar(255), status bigint, memory bigint, used_storage bigint, storage bigint, version varchar(255), instance_type varchar(255), pay_mode varchar(255), uniq_vpc_id varchar(255), uniq_subnet_id varchar(255), cpu bigint, renew_flag bigint, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_nat_gateway (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, nat_gateway_id varchar(255), nat_gateway_name varchar(255), created_time varchar(255), state varchar(255), internet_max_bandwidth_out bigint, max_concurrent_connection bigint, nat_type varchar(255), vpc_id varchar(255), zone varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
