-- New Tencent Cloud Resource Tables DDL (Phase 2)

CREATE TABLE IF NOT EXISTS q_cloud_scf (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, function_name varchar(255), namespace varchar(255), description varchar(1000), runtime varchar(255), handler varchar(255), memory_size bigint, timeout bigint, status varchar(255), add_time varchar(255), mod_time varchar(255), function_type varchar(255), status_desc varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_mariadb (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_name varchar(255), project_id bigint, region varchar(255), zone varchar(255), memory bigint, storage bigint, vpc_id varchar(255), subnet_id varchar(255), status bigint, vip varchar(255), vport bigint, pay_mode varchar(255), create_time varchar(255), deadline_time varchar(255), auto_renew_flag bigint, db_version varchar(255), cpu bigint, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_dcdb (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_name varchar(255), project_id bigint, region varchar(255), zone varchar(255), memory bigint, storage bigint, vpc_id varchar(255), subnet_id varchar(255), status bigint, vip varchar(255), vport bigint, pay_mode varchar(255), create_time varchar(255), deadline_time varchar(255), auto_renew_flag bigint, db_version_id varchar(255), cpu bigint, shard_count bigint, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_ckafka (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_name varchar(255), status bigint, vpc_id varchar(255), subnet_id varchar(255), vip varchar(255), vport bigint, bandwidth bigint, disk_size bigint, zone_id varchar(255), version varchar(255), create_time varchar(255), expire_time varchar(255), region varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_rocketmq (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_name varchar(255), instance_type bigint, status bigint, topic_num bigint, group_num bigint, max_topic_num bigint, max_group_num bigint, max_tps bigint, create_time varchar(255), expire_time varchar(255), region varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_ssl (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, alias varchar(255), subject_alt_name varchar(255), status varchar(255), type_name varchar(255), project_id bigint, from varchar(255), certificate_begin_time varchar(255), certificate_end_time varchar(255), insert_time bigint, issuer varchar(255), domain varchar(255), domain_count bigint, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_waf (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, domain varchar(255), instance_name varchar(255), instance_i_d varchar(255), flow_mode bigint, status bigint, edition varchar(255), create_time varchar(255), engine varchar(255), is_cdn bigint, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_cls (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, topic_name varchar(255), topic_id varchar(255), logset_name varchar(255), logset_id varchar(255), create_time varchar(255), status bigint, auto_split bigint, max_split_partitions bigint, partition_count bigint, period bigint, describe varchar(1000), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_monitor (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, namespace varchar(255), namespace_show_name varchar(255), namespace_value varchar(255), create_date varchar(255), description varchar(255), is_hidden bigint, dashboard_id varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_domain (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, domain_name varchar(255), domain_id varchar(255), created_on varchar(255), expires_on varchar(255), status varchar(255), auto_renew bigint, dns_status varchar(255), owner varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_tke (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, cluster_name varchar(255), cluster_id varchar(255), cluster_desc varchar(255), cluster_version varchar(255), cluster_os varchar(255), cluster_type varchar(255), cluster_network_settings varchar(255), cluster_node_num bigint, project_id bigint, status varchar(255), cluster_mater_node_num bigint, instance_advanced_settings varchar(255), tags varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_tcr (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, registry_name varchar(255), registry_id varchar(255), registry_type varchar(255), status varchar(255), public_domain varchar(255), region_name varchar(255), created_at varchar(255), updated_at varchar(255), delete_flag tinyint(1), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_es (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_name varchar(255), instance_id varchar(255), region varchar(255), zone varchar(255), app_id bigint, uin varchar(255), vpc_uid varchar(255), subnet_uid varchar(255), instance_version varchar(255), license_type varchar(255), mem_size bigint, disk_size bigint, node_num bigint, node_type varchar(255), status bigint, renew_flag bigint, charge_type varchar(255), deadline_time varchar(255), create_time varchar(255), web_node_type varchar(255), es_public_acl varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
