-- Phase 3 DDL

CREATE TABLE IF NOT EXISTS q_cloud_memcached (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_name varchar(255),instance_id varchar(255),project_id bigint,region varchar(255),zone varchar(255),vpc_id varchar(255),subnet_id varchar(255),vip varchar(255),vport bigint,mem_size bigint,status bigint,deadline_time varchar(255),create_time varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_keewidb (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_name varchar(255),instance_id varchar(255),project_id bigint,region varchar(255),zone varchar(255),vpc_id varchar(255),subnet_id varchar(255),vip varchar(255),vport bigint,mem_size bigint,status bigint,deadline_time varchar(255),create_time varchar(255),type varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_ctsdb (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_name varchar(255),instance_id varchar(255),status bigint,region varchar(255),zone varchar(255),vpc_id varchar(255),subnet_id varchar(255),vip varchar(255),vport bigint,disk_size bigint,memory bigint,create_time varchar(255),deadline_time varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_chdfs (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, file_system_name varchar(255),file_system_id varchar(255),region varchar(255),create_time varchar(255),capacity_quota bigint,status bigint, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_as (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, auto_scaling_group_name varchar(255),auto_scaling_group_id varchar(255),max_size bigint,min_size bigint,vpc_id varchar(255),subnet_id varchar(255),status varchar(255),create_time varchar(255),default_cooldown bigint,desired_capacity bigint, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_lighthouse (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_name varchar(255),instance_id varchar(255),bundle_id varchar(255),zone varchar(255),region varchar(255),status varchar(255),created_time varchar(255),expired_time varchar(255),renew_flag varchar(255),disk_size bigint,memory bigint, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_dc (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, direct_connect_name varchar(255),direct_connect_id varchar(255),access_point_id varchar(255),state varchar(255),location varchar(255),bandwidth bigint,create_time varchar(255),operator_name varchar(255),port_type varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_rabbitmq (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_name varchar(255),instance_id varchar(255),status bigint,region varchar(255),zone varchar(255),vpc_id varchar(255),subnet_id varchar(255),vip varchar(255),vport bigint,max_bandwidth bigint,max_tps bigint,create_time varchar(255),expire_time varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_apigw (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, service_name varchar(255),service_id varchar(255),protocol varchar(255),net_types varchar(255),inner_sub_domain varchar(255),outer_sub_domain varchar(255),create_time varchar(255),region varchar(255),instance_id varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_bms (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, instance_name varchar(255),instance_id varchar(255),type_id varchar(255),vpc_id varchar(255),subnet_id varchar(255),status varchar(255),zone varchar(255),private_ip_addresses varchar(255),create_time varchar(255),expired_time varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_tdmq (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, cluster_name varchar(255),cluster_id varchar(255),status bigint,create_time varchar(255),remark varchar(255),version varchar(255),public_end_point varchar(255),internal_end_point varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_oceanus (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, job_name varchar(255),job_id varchar(255),job_type bigint,status bigint,region varchar(255),create_time varchar(255),update_time varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_emr (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, cluster_name varchar(255),cluster_id varchar(255),status bigint,region varchar(255),zone varchar(255),vpc_id varchar(255),subnet_id varchar(255),master_ip varchar(255),slave_node_num bigint,create_time varchar(255),expired_time varchar(255),software_version varchar(255), PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS q_cloud_gaap (pk int NOT NULL AUTO_INCREMENT, conf_name varchar(255), conf_provider varchar(255), conf_region varchar(255), stat_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, stat_date date NOT NULL, deleted tinyint NOT NULL DEFAULT 0, proxy_name varchar(255),proxy_id varchar(255),project_id bigint,region varchar(255),access_region varchar(255),protocol varchar(255),bandwidth bigint,status varchar(255),create_time varchar(255),concurrent_connections bigint, PRIMARY KEY (pk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
