name: hello
on:
  push:
    branches:
      - master
jobs:
  hello:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: print
      env:
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        gitee_user: ${{ secrets.GITEE_USER }}
      run: |
        echo $gitee_user | base64
    
